[package]
name = "rlox-lang"
version = "0.1.0"
authors = ["nifemibosun <nifemibosun70@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
